package com.like.upper.pleasure.entity

data class BaseUserInfo(
    val absentAliveAmusement: String?,
    val anotherBadGloryCab: String?,
    val bitterHalfKangaroo: String?,
    val chemicalEntranceMusicalChild: String?,
    val cruelSealCottonReligionMetalSomeone: String?,
    val dueDeliciousHealth: String?,
    val eachFlagSword: String?,
    val expensivePracticeLessParis: String?,
    val followingFamiliarAccident: String?,
    val freezingSkyMoreJoke: String?,
    val frontShipFireworksNoisyElephant: String?,
    val highLaserLivelyMotherland: String?,
    val hopelessZooHotMidnightTyphoon: String?,
    val juicySureAuthorBusiness: String?,
    val lameVaseSuchDeadlineMarket: String?,
    val lemonTurkeyDrunkDarkness: String?,
    val liveExpressionTurkeySocialistAnger: String?,
    val looseChickTooth: String?,
    val maleMostTheme: String?,
    val merryAidsServant: String?,
    val primaryFuel: String?,
    val rightSmellCloseGlass: String?,
    val seniorPedestrianElectricalRain: String?,
    val standardLatestQuietRevision: String?,
    val straightSimpleShirtIdiom: String?,
    val strongSpringCock: String?,
    val suddenNoseAnimal: String?,
    val thankfulChemistGaySickness: String?,
    val tinyCrossroadsBellyTiresomeHat: String?,
    val triangleThatStandardDeed: String?,
    val trueTennisTightYear: String?,
    val uncertainMustardDecisionString: String?,
    val youngPresentationDifficultFailureNeitherPhotograph: String?,
    val undergroundMoreStomachTap: String?
)